"""Issue creator for the flywheel system."""

from __future__ import annotations

import hashlib
import json
import os
import time
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Optional

import structlog

from flywheel.github import create_issue, get_recent_issues

logger = structlog.get_logger("flywheel.issue_creator")

# Labels applied to all flywheel issues
FLYWHEEL_LABELS = ["flywheel-candidate", "customer-zero"]

# Components that can be used as labels
VALID_COMPONENTS = {
    "health",
    "wal",
    "logs",
    "splunk",
    "classifier",
    "ner",
    "extractor",
    "validator",
    "destination",
    "pipeline",
    "wal",
    "unknown",
}


@dataclass
class IssueSpec:
    """Specification for a GitHub issue."""

    component: str
    short_description: str
    detection_timestamp: str = ""
    error_signature: str = ""
    sample_data: list[str] = field(default_factory=list)
    suggested_investigation: str = ""
    splunk_link: str = ""
    extra_labels: list[str] = field(default_factory=list)

    def __post_init__(self) -> None:
        if not self.detection_timestamp:
            self.detection_timestamp = datetime.utcnow().isoformat() + "Z"
        if not self.error_signature:
            self.error_signature = self._compute_signature()

    def _compute_signature(self) -> str:
        """Compute a hash of the error pattern for deduplication."""
        raw = json.dumps(
            {
                "component": self.component,
                "description": self.short_description,
                "samples": self.sample_data[:3],
            },
            sort_keys=True,
        )
        return hashlib.sha256(raw.encode()).hexdigest()[:16]


def create_flywheel_issue(spec: IssueSpec) -> Optional[int]:
    """Create a GitHub issue from an issue spec.

    Args:
        spec: The issue specification

    Returns:
        The issue number if created, None if duplicate or failed.
    """
    # Validate component
    component = spec.component.lower()
    if component not in VALID_COMPONENTS:
        component = "unknown"

    # Build title
    title = f"[{component}] {spec.short_description}"

    # Build body
    body = _build_issue_body(spec)

    # Build labels
    labels = list(FLYWHEEL_LABELS)
    labels.append(component)
    labels.extend(spec.extra_labels)

    # Check for duplicate within 24h
    if _is_duplicate(component, spec.error_signature):
        logger.info("Duplicate detected, skipping", component=component, signature=spec.error_signature)
        return None

    # Create issue
    issue = create_issue(title=title, body=body, labels=labels)
    if issue:
        return issue.number
    return None


def _build_issue_body(spec: IssueSpec) -> str:
    """Build the markdown body for a flywheel issue."""
    lines = [
        f"## Detection",
        f"- **Timestamp**: {spec.detection_timestamp}",
        f"- **Component**: {spec.component}",
        f"- **Error Signature**: `{spec.error_signature}`",
        "",
    ]

    if spec.sample_data:
        lines.append("## Sample Data")
        lines.append("(anonymized)")
        lines.append("")
        for i, sample in enumerate(spec.sample_data[:5], 1):
            lines.append(f"{i}. ```")
            lines.append(f"    {sample[:500]}")
            lines.append(f"    ```")
        lines.append("")

    if spec.suggested_investigation:
        lines.append("## Suggested Investigation")
        lines.append(spec.suggested_investigation)
        lines.append("")

    if spec.splunk_link:
        lines.append("## Related Logs")
        lines.append(f"[View in Splunk]({spec.splunk_link})")
        lines.append("")

    lines.extend([
        "---",
        f"*Generated by Shrike Flywheel at {datetime.utcnow().isoformat()}Z*",
    ])

    return "\n".join(lines)


def _is_duplicate(component: str, signature: str, hours: int = 24) -> bool:
    """Check if a similar issue exists within the window.

    Args:
        component: Component name
        signature: Error signature hash
        hours: Window in hours

    Returns:
        True if duplicate found, False otherwise.
    """
    try:
        recent = get_recent_issues(component, hours=hours)

        for issue in recent:
            # Check body for same signature
            body = issue.body or ""
            if signature in body:
                return True

            # Check for similar title
            title = issue.title.lower()
            if component.lower() in title:
                # Check if created recently (within 1 hour)
                created = issue.created_at
                age_seconds = (datetime.utcnow() - created.replace(tzinfo=None)).total_seconds()
                if age_seconds < 3600:
                    return True

        return False
    except Exception as e:
        logger.warning("Duplicate check failed", error=str(e))
        return False


def build_investigation_steps(component: str, issue_type: str) -> str:
    """Build suggested investigation steps for a component/issue type.

    Args:
        component: The affected component
        issue_type: The type of issue

    Returns:
        Markdown formatted investigation steps.
    """
    steps_map = {
        "health": {
            "unhealthy": (
                "1. Check container logs: `docker logs shrike`\n"
                "2. Check resource usage: `docker stats shrike`\n"
                "3. Verify WAL health: `curl http://shrike:8080/health`"
            ),
            "latency_spike": (
                "1. Check current load: `docker stats shrike`\n"
                "2. Review WAL pending: `curl http://shrike:8080/health`\n"
                "3. Check Splunk for backpressure events"
            ),
            "oom": (
                "1. Check memory limits in docker-compose\n"
                "2. Review WAL size: `ls -lh /data/wal/`\n"
                "3. Consider increasing memory or reducing batch size"
            ),
        },
        "wal": {
            "extraction_failure": (
                "1. Check pattern library: `ls patterns/`\n"
                "2. Review failed events in WAL\n"
                "3. Test with sample log: `shrike --input sample.log --detect-only`"
            ),
            "routing_failure": (
                "1. Check destination health: `curl http://shrike:8080/health`\n"
                "2. Verify Splunk connectivity\n"
                "3. Check WAL pending count"
            ),
        },
        "logs": {
            "error": (
                "1. Review full log context in Splunk\n"
                "2. Check component health\n"
                "3. Verify configuration"
            ),
        },
        "splunk": {
            "high_classification_error": (
                "1. Check classifier model: `ls models/classifier/`\n"
                "2. Review misclassified samples in Splunk\n"
                "3. Consider retraining with new samples"
            ),
            "low_extraction_quality": (
                "1. Check pattern coverage: `ls patterns/`\n"
                "2. Review low-quality extractions in Splunk\n"
                "3. Add new patterns for missing formats"
            ),
        },
    }

    component_steps = steps_map.get(component, {})
    return component_steps.get(issue_type, "1. Review component logs\n2. Check configuration\n3. Verify connectivity")


def get_splunk_link(component: str, time_range: str = "-1h") -> str:
    """Build a Splunk search link for a component.

    Args:
        component: Component to search for
        time_range: Time range for search

    Returns:
        Splunk search URL.
    """
    base_url = os.getenv("SPLUNK_URL", "https://splunk.themillertribe-int.org")
    search = f'search index="ocsf-*" sourcetype="shrike" {component} error'
    encoded = search.replace(" ", "%20")
    return f"{base_url}/en-US/app/search/search?{encoded}&earliest={time_range}"