"""Correlation alert data structure."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any


@dataclass
class CorrelationAlert:
    """Alert generated by correlation engine."""

    alert_id: str
    timestamp: datetime | str
    correlation_type: str  # "sigma", "pattern", "anomaly"
    severity: str  # "critical", "high", "medium", "low"
    title: str
    description: str

    # Matching context
    matched_rules: list[str] = field(default_factory=list)
    matched_patterns: list[str] = field(default_factory=list)

    # Observable context
    observables: list[dict[str, Any]] = field(default_factory=list)
    event_count: int = 0

    # MITRE ATT&CK
    mitre_techniques: list[str] = field(default_factory=list)
    mitre_tactics: list[str] = field(default_factory=list)

    # Event references
    event_ids: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "alert_id": self.alert_id,
            "timestamp": self.timestamp.isoformat() if isinstance(self.timestamp, datetime) else str(self.timestamp),
            "correlation_type": self.correlation_type,
            "severity": self.severity,
            "title": self.title,
            "description": self.description,
            "matched_rules": self.matched_rules,
            "matched_patterns": self.matched_patterns,
            "observables": self.observables,
            "event_count": self.event_count,
            "mitre_techniques": self.mitre_techniques,
            "mitre_tactics": self.mitre_tactics,
            "event_ids": self.event_ids,
        }
